# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dist_mem_gen_dm/dist_mem_gen_dm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_dm || ORIG_REF_NAME==dist_mem_gen_dm} -quiet] -quiet
