# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache C:/Users/jjboy/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-16056-Firstputve/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.cache/wt [current_project]
set_property parent.project_path C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/coe/instruction.coe
read_verilog -library xil_defaultlib {
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/ALU.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/AMRegister.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/AMStage.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/CondUnite.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/CtrUnite.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/Extent.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/IDRegister.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/IDStage.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/IERegister.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/IEStage.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/Mux2.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/Mux2_32.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/Mux3_32.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/RegFile.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/WBRegister.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/arm.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/eqcmp.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/hazard.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/ifstage.v
  C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/ip/dist_mem_gen_dm/dist_mem_gen_dm.xci
set_property used_in_implementation false [get_files -all c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/dist_mem_gen_dm/dist_mem_gen_dm_ooc.xdc]

read_ip -quiet C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/ip/dist_mem_im/dist_mem_im.xci
set_property used_in_implementation false [get_files -all c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/dist_mem_im/dist_mem_im_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/utils_1/imports/synth_1/IEStage.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
