# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/ip/dist_mem_im/dist_mem_im.xci
# IP: The module: 'dist_mem_im' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/dist_mem_im/dist_mem_im_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_im'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.srcs/sources_1/ip/dist_mem_im/dist_mem_im.xci
# IP: The module: 'dist_mem_im' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jjboy/ArmPipleCPU/ArmPipleCPU.gen/sources_1/ip/dist_mem_im/dist_mem_im_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_im'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
